FROM arm32v7/debian:buster-slim
COPY qemu-arm-static /usr/bin
LABEL maintainer="dragonchaser <crichter@suse.de>"
RUN apt-get update && apt-get install -y libssl-dev libffi-dev python3-pip libopenjp2-7 python3-libtiff python3-six
RUN pip3 install cryptography
RUN pip3 install matrix-synapse
EXPOSE 8448
EXPOSE 8008
RUN useradd -ms /bin/bash -d /synapse synapse
USER synapse
WORKDIR /synapse
CMD synctl start --no-daemonize
