FROM arm32v7/debian:buster-slim
COPY qemu-arm-static /usr/bin
LABEL maintainer="dragonchaser <crichter@suse.de>"
RUN apt-get update && apt-get install -y python3-pip libopenjp2-7 python3-libtiff
RUN pip3 install matrix-synapse
WORKDIR /synapse
CMD synctl start
